# Generated by Django 4.2.5 on 2023-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время тренировки')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=20, verbose_name='День тренировки')),
                ('repeat', models.BooleanField(default=False, verbose_name='Повторять каждую неделю?')),
                ('place', models.CharField(max_length=20, verbose_name='Место проведения')),
                ('address', models.CharField(max_length=20, verbose_name='Адрес проведения')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('tel_number', models.CharField(help_text='В формате: 8000000000', max_length=11, verbose_name='Телефон')),
                ('telegram_id', models.IntegerField(blank=True, null=True, verbose_name='Телеграм ID')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
