# Generated by Django 4.2.5 on 2023-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1992-01-16', verbose_name='День рождения'),
            preserve_default=False,
        ),
    ]
