# Generated by Django 4.2.5 on 2023-09-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newbie',
            field=models.BooleanField(default=False, verbose_name='Новичок?'),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(default=False, verbose_name='Запись подтверждена')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата тренировки')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.training', verbose_name='Тренировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.user', verbose_name='Участник')),
            ],
        ),
    ]
