# Generated by Django 4.2.5 on 2023-09-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0003_user_newbie_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
    ]
