# Generated by Django 4.2.5 on 2023-09-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0006_rate_journal_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журнал'},
        ),
    ]
