# Generated by Django 4.2.5 on 2023-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0007_alter_journal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='was_end',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
    ]
