# Generated by Django 4.2.5 on 2023-09-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0008_training_was_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='was_notified',
            field=models.BooleanField(default=False),
        ),
    ]
