# Generated by Django 4.2.5 on 2023-09-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0009_journal_was_notified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='was_notified',
            new_name='second_not',
        ),
    ]
