# Generated by Django 4.2.5 on 2023-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0010_rename_was_notified_journal_second_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка от новичков'),
        ),
        migrations.AlterField(
            model_name='training',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес проведения'),
        ),
        migrations.AlterField(
            model_name='training',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Место проведения'),
        ),
    ]
