# Generated by Django 4.2.5 on 2023-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0011_alter_rate_rate_alter_training_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
