# Generated by Django 4.2.5 on 2023-09-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0012_alter_journal_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка от новичков'),
        ),
    ]
