# Generated by Django 4.2.5 on 2023-09-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0013_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='accept',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Запись подтверждена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_number',
            field=models.CharField(help_text='В формате: 8000000000', max_length=16, verbose_name='Телефон'),
        ),
    ]
