# Generated by Django 4.2.5 on 2023-09-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0014_alter_journal_accept_alter_user_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='accept',
            field=models.BooleanField(blank=True, null=True, verbose_name='Запись подтверждена'),
        ),
    ]
