# Generated by Django 4.2.5 on 2023-09-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0015_alter_journal_accept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('incoming_msg_id', models.BigIntegerField()),
                ('outgoing_msg_id', models.BigIntegerField()),
            ],
        ),
    ]
