# Generated by Django 4.2.5 on 2023-09-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0016_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал тренировок', 'verbose_name_plural': 'Журнал тренировок'},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('users', models.ManyToManyField(to='shedule_app.user', verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='GameJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(blank=True, null=True, verbose_name='Запись подтверждена')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата игры')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Журнал игр',
                'verbose_name_plural': 'Журнал игр',
            },
        ),
    ]
