# Generated by Django 4.2.5 on 2023-09-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0017_game_alter_journal_options_team_gamejournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='shedule_app.team', verbose_name='Команда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='was_end',
            field=models.BooleanField(default=False),
        ),
    ]
