# Generated by Django 4.2.5 on 2023-09-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0018_game_team_game_was_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamejournal',
            name='address',
        ),
    ]
