# Generated by Django 4.2.5 on 2023-09-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0019_remove_gamejournal_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='was_end',
        ),
        migrations.RemoveField(
            model_name='gamejournal',
            name='accept',
        ),
    ]
