# Generated by Django 4.2.5 on 2023-09-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0020_remove_game_was_end_remove_gamejournal_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shedule_app.team', verbose_name='Команда'),
        ),
    ]
