# Generated by Django 4.2.5 on 2023-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0022_journal_answer_time_journal_previuos_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ID'),
        ),
    ]
