# Generated by Django 4.2.5 on 2023-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0024_alter_rate_address_alter_rate_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='route',
            field=models.URLField(default=123, verbose_name='Ссылка на маршрут'),
            preserve_default=False,
        ),
    ]
