# Generated by Django 4.2.5 on 2023-10-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0025_training_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='route',
            field=models.URLField(default=123, verbose_name='Ссылка на маршрут'),
            preserve_default=False,
        ),
    ]
