# Generated by Django 4.2.5 on 2023-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '0027_gamejournal_accept_gamejournal_answer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejournal',
            name='previuos_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
