# Generated by Django 4.2.5 on 2023-11-16 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('route', models.URLField(verbose_name='Ссылка на маршрут')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('incoming_msg_id', models.BigIntegerField()),
                ('outgoing_msg_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес проведения')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Оценка Тренировки',
                'verbose_name_plural': 'Оценки Тренировок',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время тренировки')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=20, verbose_name='День тренировки')),
                ('repeat', models.BooleanField(default=False, verbose_name='Повторять каждую неделю?')),
                ('place', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес проведения')),
                ('was_end', models.BooleanField(default=False, verbose_name='Завершена')),
                ('route', models.URLField(verbose_name='Ссылка на маршрут')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('tel_number', models.CharField(help_text='В формате: 8000000000', max_length=16, verbose_name='Телефон')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('newbie', models.BooleanField(default=False, verbose_name='Новичок?')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('users', models.ManyToManyField(to='shedule_app.user', verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(blank=True, null=True, verbose_name='Запись подтверждена')),
                ('answer_time', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('previuos_answer', models.BooleanField(blank=True, null=True)),
                ('second_not', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата тренировки')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.training', verbose_name='Тренировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Журнал тренировок',
                'verbose_name_plural': 'Журнал тренировок',
            },
        ),
        migrations.CreateModel(
            name='GameJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата игры')),
                ('accept', models.BooleanField(blank=True, null=True, verbose_name='Запись подтверждена')),
                ('previuos_answer', models.BooleanField(blank=True, null=True)),
                ('answer_time', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule_app.user', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Журнал игр',
                'verbose_name_plural': 'Журнал игр',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shedule_app.team', verbose_name='Команда'),
        ),
    ]
