# Generated by Django 4.2.5 on 2023-11-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
