# Generated by Django 4.2.5 on 2023-11-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '5003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
