# Generated by Django 4.2.5 on 2023-11-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule_app', '5004_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата тренировки'),
        ),
    ]
